# Generated by Django 5.1.6 on 2026-07-27 09:51

import common.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset_tag', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('model_number', models.CharField(blank=True, max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('under_maintenance', 'Under Maintenance'), ('retired', 'Retired'), ('lost', 'Lost'), ('disposed', 'Disposed')], db_index=True, default='available', max_length=24)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('useful_life_years', models.PositiveSmallIntegerField(default=5)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance')], default='straight_line', max_length=24)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Book value, recomputed on save and by the monthly job.', max_digits=12)),
                ('warranty_expiry', models.DateField(blank=True, db_index=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/images/%Y/%m/', validators=[common.validators.FileValidator(allowed_content_types={'image/jpeg', 'image/png', 'image/webp'}, allowed_extensions={'.jpeg', '.jpg', '.png', '.webp'}, max_mb=5)])),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='masters.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='masters.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='masters.location')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='masters.vendor')),
            ],
            options={
                'db_table': 'assets',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssetTagCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'asset tag counter',
                'db_table': 'asset_tag_counters',
                'unique_together': {('prefix', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='assets/documents/%Y/%m/', validators=[common.validators.FileValidator(max_mb=10)])),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.asset')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'category'], name='idx_asset_status_category'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'is_deleted'], name='idx_asset_status_deleted'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['department', 'status'], name='idx_asset_dept_status'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['warranty_expiry'], name='idx_asset_warranty'),
        ),
    ]
