# Generated by Django 5.1.6 on 2026-07-27 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('checkout', 'Check-out'), ('checkin', 'Check-in')], max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('days_held', models.PositiveIntegerField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_assignments',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['asset', '-created_at'], name='idx_assign_asset_date'), models.Index(fields=['user', '-created_at'], name='idx_assign_user_date')],
            },
        ),
    ]
