# Generated by Django 5.1.6 on 2026-07-28 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('asset_assigned', 'Asset assigned to you'), ('asset_checked_in', 'Asset returned'), ('request_submitted', 'Asset request awaiting approval'), ('request_approved', 'Request approved'), ('request_rejected', 'Request rejected'), ('maintenance_scheduled', 'Maintenance scheduled'), ('maintenance_due', 'Maintenance due'), ('maintenance_completed', 'Maintenance completed'), ('warranty_expiring', 'Warranty expiring'), ('purchase_received', 'Purchase order received')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=60)),
                ('related_object_id', models.CharField(blank=True, max_length=40)),
                ('link', models.CharField(blank=True, help_text='Frontend path this notification points at.', max_length=255)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'is_read'], name='idx_notif_user_read'), models.Index(fields=['user', '-created_at'], name='idx_notif_user_date')],
            },
        ),
    ]
