# Generated by Django 5.1.15 on 2026-07-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('restore', 'Restored'), ('assign', 'Assigned'), ('checkin', 'Checked in'), ('retire', 'Retired'), ('request', 'Requested'), ('approve', 'Approved'), ('reject', 'Rejected'), ('cancel', 'Cancelled'), ('login', 'Signed in'), ('login_failed', 'Sign-in failed'), ('logout', 'Signed out'), ('password_change', 'Password changed'), ('password_reset', 'Password reset')], db_index=True, max_length=24),
        ),
    ]
