# Generated by Django 5.1.6 on 2026-07-28 05:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_assetrequest'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('calibration', 'Calibration'), ('upgrade', 'Upgrade'), ('other', 'Other')], default='corrective', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=16)),
                ('scheduled_date', models.DateField(help_text='When the work is booked for.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('technician', models.CharField(blank=True, help_text="Person doing the work, when it isn't a vendor.", max_length=150)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Captured on completion.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('asset_status_before', models.CharField(blank=True, max_length=24)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.asset')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_maintenance', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='masters.vendor')),
            ],
            options={
                'db_table': 'maintenance_records',
                'ordering': ('-scheduled_date', '-id'),
                'indexes': [models.Index(fields=['asset', '-scheduled_date'], name='idx_maint_asset_date'), models.Index(fields=['status', 'scheduled_date'], name='idx_maint_status_date')],
            },
        ),
    ]
