/**
 * Asset lifecycle mutations (FR-14.11).
 *
 * Three things every one of these gets:
 *
 * * **An idempotency key per submission** (BE-4), generated once when the user
 *   commits and reused for every retry of *that* attempt. A new key per retry
 *   would defeat the mechanism entirely — the whole point is that the server
 *   recognises the second attempt as the same action.
 * * **An optimistic update**, so the screen reflects the decision immediately.
 *   On a bad connection the alternative is a spinner over an action the person
 *   has already physically performed.
 * * **A rollback that restores the exact previous value**, not a refetch. A
 *   refetch on failure is another request that can also fail, leaving the UI
 *   showing a state that never existed.
 */
import { useMutation, useQueryClient } from "@tanstack/react-query";
import * as Crypto from "expo-crypto";

import { ApiError, api } from "@/api";
import type { AssetDetail, User } from "@/api";

export function newIdempotencyKey(): string {
  return Crypto.randomUUID();
}

interface AssignInput {
  assetId: number;
  user: User;
  notes?: string;
  /** Generated by the caller when the form is submitted, so retries reuse it. */
  idempotencyKey: string;
}

interface CheckinInput {
  assetId: number;
  notes?: string;
  locationId?: number | null;
  idempotencyKey: string;
}

/** A 409 is not a failure of the request — it is the server reporting that the
 *  world moved. It needs its own path through the UI (§12.5). */
export function isConflict(error: unknown): error is ApiError {
  return error instanceof ApiError && error.isConflict;
}

function useAssetMutation<TInput extends { assetId: number }>(
  run: (input: TInput) => Promise<AssetDetail>,
  optimistic: (previous: AssetDetail, input: TInput) => AssetDetail,
) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: run,

    async onMutate(input) {
      const key = ["asset", input.assetId];
      // Stop an in-flight refetch from overwriting the optimistic value the
      // moment after we set it.
      await queryClient.cancelQueries({ queryKey: key });

      const previous = queryClient.getQueryData<AssetDetail>(key);
      if (previous) {
        queryClient.setQueryData<AssetDetail>(key, optimistic(previous, input));
      }
      return { previous };
    },

    onError(_error, input, context) {
      // Exactly what was there before, not a refetch — see the note above.
      if (context?.previous) {
        queryClient.setQueryData(["asset", input.assetId], context.previous);
      }
    },

    onSuccess(asset, input) {
      // The server's own copy wins over the optimistic guess.
      queryClient.setQueryData(["asset", input.assetId], asset);
      queryClient.invalidateQueries({ queryKey: ["asset", input.assetId, "history"] });
    },

    onSettled(_data, _error, input) {
      // Lists show status and holder, so they are stale either way — including
      // after a 409, where the truth is whatever the other person did.
      queryClient.invalidateQueries({ queryKey: ["assets"] });
      queryClient.invalidateQueries({ queryKey: ["asset", input.assetId] });
    },
  });
}

export function useAssignAsset() {
  return useAssetMutation<AssignInput>(
    ({ assetId, user, notes, idempotencyKey }) =>
      api.post<AssetDetail>(
        `/assets/${assetId}/assign/`,
        { user_id: user.id, notes: notes ?? "" },
        { idempotencyKey },
      ),
    (previous, { user }) => ({
      ...previous,
      status: "assigned",
      status_label: "Assigned",
      assigned_to: user,
      assigned_at: new Date().toISOString(),
    }) as AssetDetail,
  );
}

export function useCheckinAsset() {
  return useAssetMutation<CheckinInput>(
    ({ assetId, notes, locationId, idempotencyKey }) =>
      api.post<AssetDetail>(
        `/assets/${assetId}/checkin/`,
        {
          notes: notes ?? "",
          ...(locationId ? { location_id: locationId } : {}),
        },
        { idempotencyKey },
      ),
    (previous) => ({
      ...previous,
      status: "available",
      status_label: "Available",
      assigned_to: null,
      assigned_at: null,
    }) as AssetDetail,
  );
}
