/**
 * Asset lifecycle mutations (FR-14.11).
 *
 * Three things every one of these gets:
 *
 * * **An idempotency key per submission** (BE-4), generated once when the user
 *   commits and reused for every retry of *that* attempt. A new key per retry
 *   would defeat the mechanism entirely — the whole point is that the server
 *   recognises the second attempt as the same action.
 * * **An optimistic update**, so the screen reflects the decision immediately.
 *   On a bad connection the alternative is a spinner over an action the person
 *   has already physically performed.
 * * **A rollback that restores the exact previous value**, not a refetch. A
 *   refetch on failure is another request that can also fail, leaving the UI
 *   showing a state that never existed.
 */
import { onlineManager, useMutation, useQueryClient } from "@tanstack/react-query";
import * as Crypto from "expo-crypto";

import { ApiError, api } from "@/api";
import type { AssetDetail, User } from "@/api";
import { queue, queuedMutation } from "@/offline/queue";
import type { QueuedMutation } from "@/offline/queue";

export function newIdempotencyKey(): string {
  return Crypto.randomUUID();
}

interface AssignInput {
  assetId: number;
  user: User;
  notes?: string;
  /** Generated by the caller when the form is submitted, so retries reuse it. */
  idempotencyKey: string;
}

interface CheckinInput {
  assetId: number;
  notes?: string;
  locationId?: number | null;
  idempotencyKey: string;
}

/** A 409 is not a failure of the request — it is the server reporting that the
 *  world moved. It needs its own path through the UI (§12.5). */
export function isConflict(error: unknown): error is ApiError {
  return error instanceof ApiError && error.isConflict;
}

/** Non-null when the action was queued rather than sent. */
export type MutationOutcome = { queued: true } | { queued: false; asset: AssetDetail };

function useAssetMutation<TInput extends { assetId: number }>(
  run: (input: TInput) => Promise<AssetDetail>,
  optimistic: (previous: AssetDetail, input: TInput) => AssetDetail,
  describe: (input: TInput) => QueuedMutation,
) {
  const queryClient = useQueryClient();

  return useMutation<MutationOutcome, unknown, TInput, { previous?: AssetDetail }>({
    async mutationFn(input) {
      // Offline, the action is written to the queue instead of thrown away.
      // The optimistic update below stays on screen, marked pending, and the
      // queue sends it when the signal returns — carrying the idempotency key
      // minted here, so a resend after a crash applies once.
      if (!onlineManager.isOnline()) {
        await queue.enqueue(describe(input));
        return { queued: true };
      }
      return { queued: false, asset: await run(input) };
    },

    async onMutate(input) {
      const key = ["asset", input.assetId];
      // Stop an in-flight refetch from overwriting the optimistic value the
      // moment after we set it.
      await queryClient.cancelQueries({ queryKey: key });

      const previous = queryClient.getQueryData<AssetDetail>(key);
      if (previous) {
        queryClient.setQueryData<AssetDetail>(key, optimistic(previous, input));
      }
      return { previous };
    },

    onError(_error, input, context) {
      // Exactly what was there before, not a refetch — see the note above.
      if (context?.previous) {
        queryClient.setQueryData(["asset", input.assetId], context.previous);
      }
    },

    onSuccess(outcome, input) {
      // Nothing came back from a queued action, so the optimistic value is the
      // best truth available and must be left alone. Overwriting it with the
      // server's stale copy would undo the change in front of the user.
      if (outcome.queued) return;

      // The server's own copy wins over the optimistic guess.
      queryClient.setQueryData(["asset", input.assetId], outcome.asset);
      queryClient.invalidateQueries({ queryKey: ["asset", input.assetId, "history"] });
    },

    onSettled(outcome, _error, input) {
      // Refetching a queued action's asset would replace the optimistic state
      // with the server's unchanged copy — the change would visibly vanish.
      if (outcome?.queued) return;

      // Lists show status and holder, so they are stale either way — including
      // after a 409, where the truth is whatever the other person did.
      queryClient.invalidateQueries({ queryKey: ["assets"] });
      queryClient.invalidateQueries({ queryKey: ["asset", input.assetId] });
    },
  });
}

export function useAssignAsset() {
  return useAssetMutation<AssignInput>(
    ({ assetId, user, notes, idempotencyKey }) =>
      api.post<AssetDetail>(
        `/assets/${assetId}/assign/`,
        { user_id: user.id, notes: notes ?? "" },
        { idempotencyKey },
      ),
    (previous, { user }) => ({
      ...previous,
      status: "assigned",
      status_label: "Assigned",
      assigned_to: user,
      assigned_at: new Date().toISOString(),
    }) as AssetDetail,
    ({ assetId, user, notes }) =>
      queuedMutation({
        method: "POST",
        path: `/assets/${assetId}/assign/`,
        body: { user_id: user.id, notes: notes ?? "" },
        kind: "assign",
        subject: { type: "asset", id: assetId },
      }),
  );
}

export function useCheckinAsset() {
  return useAssetMutation<CheckinInput>(
    ({ assetId, notes, locationId, idempotencyKey }) =>
      api.post<AssetDetail>(
        `/assets/${assetId}/checkin/`,
        {
          notes: notes ?? "",
          ...(locationId ? { location_id: locationId } : {}),
        },
        { idempotencyKey },
      ),
    (previous) => ({
      ...previous,
      status: "available",
      status_label: "Available",
      assigned_to: null,
      assigned_at: null,
    }) as AssetDetail,
    ({ assetId, notes, locationId }) =>
      queuedMutation({
        method: "POST",
        path: `/assets/${assetId}/checkin/`,
        body: { notes: notes ?? "", ...(locationId ? { location_id: locationId } : {}) },
        kind: "checkin",
        subject: { type: "asset", id: assetId },
      }),
  );
}
