# Generated by Django 5.1.15 on 2026-07-29 05:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_assetrequest'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], db_index=True, default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_takes', to='masters.location')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_takes', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_stock_takes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_takes',
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockTakeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('found', 'Found'), ('missing', 'Missing'), ('unexpected', 'Unexpected')], db_index=True, max_length=20)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_entries', to='assets.asset')),
                ('expected_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_take_entries', to='masters.location')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_take_scans', to=settings.AUTH_USER_MODEL)),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='stocktake.stocktake')),
            ],
            options={
                'db_table': 'stock_take_entries',
                'ordering': ('state', 'asset__asset_tag'),
            },
        ),
        migrations.AddIndex(
            model_name='stocktake',
            index=models.Index(fields=['location', 'status'], name='idx_stocktake_loc_status'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeentry',
            constraint=models.UniqueConstraint(fields=('stock_take', 'asset'), name='uniq_stocktake_asset'),
        ),
    ]
